import "./globals.css"
import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import github from "../public/gh.svg"
import BrandIcons from "./_components/BrandIcons"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="sans-serif min-h-screen max-w-screen-lg bg-slate-950 p-1.5 text-slate-200 lg:mx-auto  lg:p-0">
        <nav className="mt-5 flex items-center border-b pb-4">
          <span className="underline-red grow text-xl font-bold">
            JoseHöwer
          </span>
          <div className="flex items-center">
            <Link
              href="/blog"
              className="mr-3 rounded-sm border-2 border-neon-red px-4 py-2 hover:bg-neon-red"
            >
              Blog
            </Link>
            <Link
              href="https://github.com/Josehower"
              target="_blank"
              className="mr-3 "
            >
              <BrandIcons brand="GitHub" />
            </Link>
            <Link
              href="https://www.linkedin.com/in/josehower"
              target="_blank"
              className="mr-3 "
            >
              <BrandIcons brand="Linkedin" />
            </Link>
            <Link
              href="https://twitter.com/HowerBarbosa"
              target="_blank"
              className=""
            >
              <BrandIcons brand="X" />
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
